# Generated by Django 5.0.4 on 2024-10-21 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=250)),
                ('fecha_nacimiento', models.DateField()),
                ('nombre_usuario', models.CharField(max_length=100)),
                ('contrasena', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('leido', models.BooleanField(default=False)),
                ('tipo', models.CharField(choices=[('texto', 'Texto'), ('foto', 'Foto'), ('video', 'Video'), ('archivo', 'Archivo')], max_length=10)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='archivos/')),
                ('emisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_enviados', to='chat.usuario')),
                ('receptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_recibidos', to='chat.usuario')),
            ],
        ),
    ]
