# Generated by Django 5.0.4 on 2024-10-21 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('admin', 'Administrador'), ('trabajador', 'Trabajador de área')], default='trabajador', max_length=10),
        ),
    ]
