# Generated by Django 5.0.4 on 2024-11-04 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_usuario_tipo_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=250)),
                ('categoria', models.CharField(max_length=50)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('prospecto', 'Prospecto'), ('inactivo', 'Inactivo')], default='activo', max_length=10)),
            ],
        ),
    ]
