# Generated by Django 5.0.4 on 2024-11-07 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_oportunidad_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oportunidad',
            name='descripcion',
            field=models.TextField(default='Sin descripción'),
        ),
    ]
