# Generated by Django 5.0.4 on 2024-11-08 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_grupochat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='categoria',
            field=models.CharField(choices=[('A', 'Cliente de alto valor'), ('B', 'Cliente de valor medio'), ('C', 'Cliente de bajo valor'), ('VIP', 'Cliente muy importante'), ('Nuevo', 'Cliente nuevo'), ('Frecuente', 'Cliente frecuente'), ('Ocasional', 'Cliente ocasional')], default='A', max_length=10),
        ),
    ]
