# Generated by Django 5.0.4 on 2024-11-13 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_usuario_foto_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='cobranza',
            name='factura',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cobranzas', to='chat.factura'),
            preserve_default=False,
        ),
    ]
