# Generated by Django 5.0.4 on 2024-11-20 16:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0014_ingreso_origen'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='categoria',
            field=models.CharField(choices=[('A', 'Cliente de alto valor'), ('B', 'Cliente de valor medio'), ('C', 'Cliente de bajo valor'), ('VIP', 'Cliente muy importante'), ('Nuevo', 'Cliente nuevo'), ('Frecuente', 'Cliente frecuente'), ('Ocasional', 'Cliente ocasional')], default='Nuevo', max_length=10),
        ),
    ]
