# Generated by Django 5.0.4 on 2024-11-22 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0015_cliente_fecha_creacion_alter_cliente_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='dni',
            field=models.CharField(default='00000000', max_length=8, unique=True),
            preserve_default=False,
        ),
    ]
