# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - InterComercioEstudio

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'
          
      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade setuptools wheel
          # Remove the version constraint for contourpy
          sed -i 's/contourpy==1.3.0/contourpy==1.0.7/' requirements.txt
          pip install -r requirements.txt
          
      - name: Create necessary directories
        run: |
          mkdir -p static
          mkdir -p staticfiles
          mkdir -p media
          
      - name: Run migrations
        run: |
          python manage.py makemigrations
          python manage.py migrate
          
      - name: Collect static files
        run: |
          python manage.py collectstatic --noinput
          
      - name: Zip artifact for deployment
        run: zip release.zip ./* -r
        
      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            release.zip
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app
          
      - name: Unzip artifact for deployment
        run: unzip release.zip
        
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_8033D1083EA1499C8291DCC9E7E742AC }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_EA07C33E29AC455491C8EBB30CE6E58C }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_E95E497BAE234FF78DA86676CD4D4EBB }}
          
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'InterComercioEstudio'
          slot-name: 'Production'